FROM debian:stretch

RUN apt-get update \
    && apt-get install -y \
    build-essential \
    python-dev \
    python3-dev \
    python3-pip \
    wget

RUN mkdir /opt/software
ADD requirements.txt /opt/software/
ADD upload.py /opt/software/
RUN pip3 install --no-cache -r /opt/software/requirements.txt

ENTRYPOINT ["/bin/bash"]
