# Generated by Django 3.2.4 on 2021-10-23 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_publicdataset'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicdataset',
            name='file_mapping',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
