# Generated by Django 3.2.4 on 2022-02-09 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_add_metadata_to_public_datasets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='executedoperation',
            name='error_messages',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='executedoperation',
            name='inputs',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='executedoperation',
            name='outputs',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='resourcemetadata',
            name='feature_set',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resourcemetadata',
            name='observation_set',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
