# Generated by Django 3.2.12 on 2022-05-19 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_add_file_extensions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operationresource',
            old_name='file_extension',
            new_name='file_format',
        ),
        migrations.RenameField(
            model_name='resource',
            old_name='file_extension',
            new_name='file_format',
        ),
        migrations.AlterField(
            model_name='operationresource',
            name='resource_type',
            field=models.CharField(blank=True, choices=[('FQ', 'Fastq'), ('FA', 'Fasta'), ('ALN', 'Alignment (SAM/BAM)'), ('FT', 'Feature table'), ('MTX', 'Numeric table'), ('I_MTX', 'Integer table'), ('EXP_MTX', 'Expression matrix'), ('RNASEQ_COUNT_MTX', 'RNA-seq count matrix'), ('NS', 'Network descriptor'), ('ANN', 'Annotation table'), ('BED', 'BED-format file'), ('JSON', 'JSON-format file'), ('*', 'General file')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='resource_type',
            field=models.CharField(blank=True, choices=[('FQ', 'Fastq'), ('FA', 'Fasta'), ('ALN', 'Alignment (SAM/BAM)'), ('FT', 'Feature table'), ('MTX', 'Numeric table'), ('I_MTX', 'Integer table'), ('EXP_MTX', 'Expression matrix'), ('RNASEQ_COUNT_MTX', 'RNA-seq count matrix'), ('NS', 'Network descriptor'), ('ANN', 'Annotation table'), ('BED', 'BED-format file'), ('JSON', 'JSON-format file'), ('*', 'General file')], max_length=25, null=True),
        ),
    ]
