# Generated by Django 3.2.12 on 2022-05-27 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_rename_file_extension_to_file_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationresource',
            name='file_format',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='file_format',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
