# Generated by Django 4.0.6 on 2022-08-22 20:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_allow_null_file_format'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimpleResource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('path', models.FileField(upload_to='')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simple_resources', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
