# Generated by Django 4.0.6 on 2022-08-24 20:15

import api.models.operation_resource
import api.models.resource
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_allow_null_file_format'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operationresource',
            name='path',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='path',
        ),
        migrations.AddField(
            model_name='operationresource',
            name='datafile',
            #field=models.FileField(null=True, upload_to=api.models.operation_resource.upload_base),
            field=models.FileField(upload_to=api.models.operation_resource.upload_base),
        ),
        migrations.AddField(
            model_name='resource',
            name='datafile',
            #field=models.FileField(null=True, upload_to=api.models.resource.get_storage_dir),
            field=models.FileField(upload_to=api.models.resource.get_storage_dir),
        ),
    ]
