# Generated by Django 4.0.6 on 2022-09-12 13:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_resource_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='addition_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
