# Generated by Django 4.0.6 on 2022-08-24 20:41

import api.models.operation_resource
import api.models.resource
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_operationresource_path_remove_resource_path_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationresource',
            name='datafile',
            field=models.FileField(upload_to=api.models.operation_resource.upload_base),
        ),
        migrations.AlterField(
            model_name='resource',
            name='datafile',
            field=models.FileField(upload_to=api.storage.get_storage_dir),
        ),
    ]
