# Generated by Django 4.1.4 on 2023-06-22 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_globus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationresource',
            name='resource_type',
            field=models.CharField(blank=True, choices=[('FQ', 'Fastq'), ('FA', 'Fasta'), ('ALN', 'Alignment (SAM/BAM)'), ('BAI', 'BAM Index'), ('FT', 'Feature table'), ('MTX', 'Numeric table'), ('I_MTX', 'Integer table'), ('EXP_MTX', 'Expression matrix'), ('RNASEQ_COUNT_MTX', 'RNA-seq count matrix'), ('NS', 'Network descriptor'), ('ANN', 'Annotation table'), ('BED3', 'BED3-format file'), ('BED6', 'BED6-format file'), ('NRWPK', 'NarrowPeak (BED6+4) format file'), ('WIG', 'WIG (wiggle) format'), ('BIGWIG', 'BigWIG (compressed wiggle) format'), ('BEDGRAPH', 'BedGraph format'), ('JSON', 'JSON-format file'), ('*', 'General file')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='resource_type',
            field=models.CharField(blank=True, choices=[('FQ', 'Fastq'), ('FA', 'Fasta'), ('ALN', 'Alignment (SAM/BAM)'), ('BAI', 'BAM Index'), ('FT', 'Feature table'), ('MTX', 'Numeric table'), ('I_MTX', 'Integer table'), ('EXP_MTX', 'Expression matrix'), ('RNASEQ_COUNT_MTX', 'RNA-seq count matrix'), ('NS', 'Network descriptor'), ('ANN', 'Annotation table'), ('BED3', 'BED3-format file'), ('BED6', 'BED6-format file'), ('NRWPK', 'NarrowPeak (BED6+4) format file'), ('WIG', 'WIG (wiggle) format'), ('BIGWIG', 'BigWIG (compressed wiggle) format'), ('BEDGRAPH', 'BedGraph format'), ('JSON', 'JSON-format file'), ('*', 'General file')], max_length=25, null=True),
        ),
    ]
