# Generated by Django 4.1.7 on 2023-06-28 15:17

'''
Note that this is the first of three migrations which go together--
Here, we add the new model fields and set a default empty string.
In 0018, we populate existing rows with a data migration
Finally, in 0019, we set these fields to be non-null
'''

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='git_commit',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='operation',
            name='repository_url',
            field=models.URLField(default='', max_length=500),
        ),
    ]
