# Generated by Django 4.1.7 on 2023-06-28 15:33

'''
This completes the schema AND data migrations of 0017 and 0018.
Recall that in 0017, we added the git commit and repo fields. 
However, we needed to extract the values for those fields for
existing database records. That first commit allowed these fields
to be blank. We then populate in 0018 and finally set the fields
to be non-nullable here.
'''

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_operation_data_migration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='git_commit',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='operation',
            name='repository_url',
            field=models.URLField(max_length=500),
        ),
    ]
