# Generated by Django 4.1.7 on 2023-10-06 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_operation_git_commit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]