# Generated by Django 4.1.7 on 2024-02-27 13:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_allow_blank_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='executedoperation',
            name='job_id',
            field=models.CharField(default=uuid.uuid4, max_length=64, null=True),
        ),
    ]
