#!/usr/bin/env ruby
#^syntax detection

forge "https://forgeapi.puppetlabs.com"

mod 'landcareresearch-solr', '7.0.0'
mod 'puppet-nginx', '3.3.0'
mod 'puppet-python', '6.2.1'
mod 'puppet-rabbitmq', '12.0.0'
mod 'puppetlabs-docker', '4.4.0'
mod 'puppetlabs-vcsrepo', '5.0.0'

mod 'webmev-mevapi', '0.0.1', :path => './mevapi'
