#!/usr/bin/env ruby
#^syntax detection

forge "https://forgeapi.puppetlabs.com"

mod 'puppet-python', '6.1.0'
mod 'puppet-rabbitmq', '11.1.0'
mod 'puppetlabs-vcsrepo', '5.0.0'

mod 'webmev-mevapi', '0.0.1', :path => './mevapi'
